-- Schema for the Bachelor Project demonstrator.
-- This file creates the database objects needed by the Spring Boot backend,
-- including PostgreSQL row-level security policies.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS tenants (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(255) NOT NULL,
    CONSTRAINT tenants_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS roles (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT roles_name_key UNIQUE (name),
    CONSTRAINT roles_name_check CHECK (
        name IN ('PLATFORM_ADMIN', 'MANAGER', 'INSTRUCTOR', 'PARTICIPANT', 'RESEARCHER')
    )
);

CREATE TABLE IF NOT EXISTS users (
    id bigint NOT NULL,
    tenant_id uuid,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT fk_users_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE SEQUENCE IF NOT EXISTS users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE users_id_seq OWNED BY users.id;
ALTER TABLE users ALTER COLUMN id SET DEFAULT nextval('users_id_seq'::regclass);

CREATE TABLE IF NOT EXISTS user_roles (
    role_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT user_roles_pkey PRIMARY KEY (role_id, user_id),
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS questionnaires (
    created_by bigint,
    id bigint NOT NULL,
    tenant_id uuid NOT NULL,
    title character varying(255) NOT NULL,
    definition_json text NOT NULL,
    CONSTRAINT questionnaires_pkey PRIMARY KEY (id),
    CONSTRAINT fk_questionnaires_creator FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT fk_questionnaires_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE SEQUENCE IF NOT EXISTS questionnaires_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE questionnaires_id_seq OWNED BY questionnaires.id;
ALTER TABLE questionnaires ALTER COLUMN id SET DEFAULT nextval('questionnaires_id_seq'::regclass);

CREATE TABLE IF NOT EXISTS responses (
    id bigint NOT NULL,
    questionnaire_id bigint NOT NULL,
    user_id bigint,
    tenant_id uuid NOT NULL,
    answer_json text NOT NULL,
    CONSTRAINT responses_pkey PRIMARY KEY (id),
    CONSTRAINT uk_responses_questionnaire_user UNIQUE (questionnaire_id, user_id),
    CONSTRAINT fk_responses_questionnaire FOREIGN KEY (questionnaire_id) REFERENCES questionnaires(id),
    CONSTRAINT fk_responses_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_responses_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);

CREATE SEQUENCE IF NOT EXISTS responses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE responses_id_seq OWNED BY responses.id;
ALTER TABLE responses ALTER COLUMN id SET DEFAULT nextval('responses_id_seq'::regclass);

CREATE TABLE IF NOT EXISTS gap_profiles (
    id bigint NOT NULL,
    tenant_id uuid NOT NULL,
    questionnaire_id bigint NOT NULL,
    participant_id bigint NOT NULL,
    submission_id bigint NOT NULL,
    observed_level double precision NOT NULL,
    target_level double precision NOT NULL,
    gap_value double precision NOT NULL,
    gap_category character varying(20) NOT NULL,
    created_at timestamp without time zone NOT NULL,
    CONSTRAINT gap_profiles_pkey PRIMARY KEY (id),
    CONSTRAINT gap_profiles_submission_id_key UNIQUE (submission_id),
    CONSTRAINT chk_gap_profiles_category CHECK (gap_category IN ('LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT fk_gap_profiles_tenant FOREIGN KEY (tenant_id) REFERENCES tenants(id),
    CONSTRAINT fk_gap_profiles_questionnaire FOREIGN KEY (questionnaire_id) REFERENCES questionnaires(id),
    CONSTRAINT fk_gap_profiles_participant FOREIGN KEY (participant_id) REFERENCES users(id),
    CONSTRAINT fk_gap_profiles_submission FOREIGN KEY (submission_id) REFERENCES responses(id)
);

ALTER TABLE gap_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY
    (START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);

CREATE TABLE IF NOT EXISTS audit_log (
    id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    actor_user_id bigint,
    actor_email character varying(255),
    actor_roles character varying(255),
    actor_tenant_id uuid,
    action character varying(100) NOT NULL,
    outcome character varying(20) NOT NULL,
    reason character varying(255),
    request_path text,
    CONSTRAINT audit_log_pkey PRIMARY KEY (id),
    CONSTRAINT chk_audit_log_action CHECK (
        action IN (
            'QUESTIONNAIRE_CREATED',
            'SUBMISSION_CREATED',
            'GAP_PROFILE_VIEWED',
            'AUTHORIZATION_DENIED',
            'CROSS_TENANT_ACCESS_DENIED'
        )
    ),
    CONSTRAINT chk_audit_log_outcome CHECK (outcome IN ('SUCCESS', 'DENIED')),
    CONSTRAINT fk_audit_log_actor_user FOREIGN KEY (actor_user_id) REFERENCES users(id),
    CONSTRAINT fk_audit_log_actor_tenant FOREIGN KEY (actor_tenant_id) REFERENCES tenants(id)
);

ALTER TABLE audit_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY
    (START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);

CREATE OR REPLACE FUNCTION prevent_audit_log_row_changes()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'audit_log is append-only: % is not allowed', TG_OP
        USING ERRCODE = '42501';
END;
$$;

DROP TRIGGER IF EXISTS audit_log_prevent_update_delete ON audit_log;
CREATE TRIGGER audit_log_prevent_update_delete
BEFORE UPDATE OR DELETE ON audit_log
FOR EACH ROW
EXECUTE FUNCTION prevent_audit_log_row_changes();

CREATE OR REPLACE FUNCTION prevent_audit_log_truncate()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    current_role_is_superuser boolean;
BEGIN
    SELECT rolsuper
    INTO current_role_is_superuser
    FROM pg_roles
    WHERE rolname = current_user;

    IF NOT COALESCE(current_role_is_superuser, false) THEN
        RAISE EXCEPTION 'audit_log is append-only: TRUNCATE is not allowed'
            USING ERRCODE = '42501';
    END IF;

    RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS audit_log_prevent_truncate ON audit_log;
CREATE TRIGGER audit_log_prevent_truncate
BEFORE TRUNCATE ON audit_log
FOR EACH STATEMENT
EXECUTE FUNCTION prevent_audit_log_truncate();

ALTER TABLE questionnaires ENABLE ROW LEVEL SECURITY;
ALTER TABLE responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE gap_profiles ENABLE ROW LEVEL SECURITY;

ALTER TABLE questionnaires FORCE ROW LEVEL SECURITY;
ALTER TABLE responses FORCE ROW LEVEL SECURITY;
ALTER TABLE gap_profiles FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS questionnaires_tenant_isolation ON questionnaires;
CREATE POLICY questionnaires_tenant_isolation
ON questionnaires
USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid)
WITH CHECK (tenant_id = current_setting('app.current_tenant_id', true)::uuid);

DROP POLICY IF EXISTS responses_tenant_isolation ON responses;
CREATE POLICY responses_tenant_isolation
ON responses
USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid)
WITH CHECK (tenant_id = current_setting('app.current_tenant_id', true)::uuid);

DROP POLICY IF EXISTS gap_profiles_tenant_isolation ON gap_profiles;
CREATE POLICY gap_profiles_tenant_isolation
ON gap_profiles
USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid)
WITH CHECK (tenant_id = current_setting('app.current_tenant_id', true)::uuid);
